### ISSUE TITLE
Disable the conditional logic when retrieving it from the basket at the backend

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-backend#1058]
https://matter-lab.slack.com/archives/C020BBTJBME/p1621863130000400

**Comment by natalia-muzyka** [comment]
@WorldImpex I have no access to this link, could you share, please?

**Comment by WorldImpex** [comment]
@natalia-muzyka Discussion was implementation related so not much to check on this ticket. It is related to `[this bug. ](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1013)`

**Comment by natalia-muzyka** [comment]
Works as expected.
The conditional logic is disabled after transferring an item that is a part of conditional logic.
https://www.screencast.com/t/1fZL4SPMKlTY

Environment:
https://admin-staging.mindlogger.org/
https://library-staging.mindlogger.org/
Win 10 // Chrome Version 91.0.4472.101

Applets:
EDUCATE EMA applet
DBT Applet 1
Healthy Brain Network (NIMH content) v0.30
Conditional logic
