### ISSUE TITLE
Broken dependencies tree

### ISSUE THREAD

**Issue by peterpeterparker** [ChildMindInstitute/mindlogger-backend#1061]
### Actual Behavior

The dependencies tree of this admin project seems to be broken. If the project is cloned and, dependencies are fetched through `yarn install`, these are correctly installed but, serving (`npm run serve`) the admin console result in a runtime error.

> [Vuetify] Multiple instances of Vue detected
> ...
> [Vue warn]: Error in beforeCreate hook: "Error: Vuetify is not properly initialized...
> ...
> Error: Vuetify is not properly initialized, see
> ...

If the dependencies are fetched through a clean npm installation (`npm run ci`) the process end up in error as both lock and definition are not in sync.

> npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

### Expected Behavior

An up-to-date dependencies tree and, being to install the dependency and run the app without errors.

### Reproduction

Yarn error:

```
git clone https://github.com/ChildMindInstitute/mindlogger-backend
cd mindlogger-backend
yarn install
npm run serve
```

and opening the app in a browser

Npm error:

```
git clone https://github.com/ChildMindInstitute/mindlogger-backend
cd mindlogger-backend
npm ci
```

### Screenshot

Runtime error:

<img width="1117" alt="Capture d’écran 2021-05-27 à 17 11 48" src="https://user-images.githubusercontent.com/16886711/119851354-a1353c00-bf0e-11eb-8352-14bf18aee70f.png">

**Comment by devbtech** [comment]
@peterpeterparker I assume you meant `[mindlogger-admin](https://github.com/ChildMindInstitute/mindlogger-admin)`, right?  I am a little confused because you mentioned `mindlogger-backend` a few times above in the description.

**Comment by peterpeterparker** [comment]
Freak yeah sorry, I mean in the admin.

Gonna close this one and replace it with following issue: https://github.com/ChildMindInstitute/mindlogger-admin/issues/1046
