### ISSUE TITLE
prettier code formatter

### ISSUE THREAD

**Issue by peterpeterparker** [ChildMindInstitute/mindlogger-backend#1062]
### Feature Description

Add [prettier](https://prettier.io/), including husky pre-commit hook, to the project to set a common guideline for the code formatting. This will ease contributions and, reviews as any piece of codes are coding to follow the same format specifications.

### Dependency

This can be added only once #1061 solved, as dependencies have to be added

### Side note

I can provide a PR. Let me know if you have any preferences regarding the configuration of the formater.

**Comment by Matchdev120** [comment]
@WorldImpex
Do you want me to set up Husky pre-commit hook with ESLint and Prettier on mindlogger-web?

**Comment by WorldImpex** [comment]
@Matchdev120 Yes please

**Comment by peterpeterparker** [comment]
Likewise I meant in the admin project, opened a correct issue regarding it: https://github.com/ChildMindInstitute/mindlogger-backend/issues/1062

Sorry for the noise.
