### ISSUE TITLE
feature: docker-compose for local development and testing

### ISSUE THREAD

**Issue by BarrySunderland** [ChildMindInstitute/mindlogger-backend#1083]
It would be nice to be able to run the api and mongo db using docker-compose instead of installing both locally.

**Comment by WorldImpex** [comment]
@jj105 Could you confirm this is working as expected?

**Comment by jj105** [comment]
It's working fine for me.
![image.png](https://images.zenhubusercontent.com/5e565f9bd9593e11ebab005a/b3250ca5-271's ow6-486c-8ba0-b3a342852fb6)
