### ISSUE TITLE
Allow editor to upload an image file for Splash Screen 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-backend#1093]
Allow an editor to upload an image file to splash screen as well. 
* The image should take up the whole screen on mobile and be the side of an item on webapp 
* Add the size requirements in the applet builder so the editor knows what size to make the image/ gif that is being uploaded

**Comment by natalia-muzyka** [comment]
@Matchdev120 @WorldImpex could you clarify, please, what does it mean that splash screen image should be the side of an item on webapp? Currently, I  don't see any changes on webapp side.


 The size requirements in the applet builder aren't added yet. @Matchdev120 Would this be added in the scope of https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/556 ?

**Comment by WorldImpex** [comment]
@natalia-muzyka We need the webapp to be the same experience as mobile but let's create a separate ticket.

**Comment by natalia-muzyka** [comment]
**Issues:**
Splash screen isn't displayed on webapp [#213](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/213)

**Comment by natalia-muzyka** [comment]
There will be no requirements for image size, and in the current milestone for images format as the backend can automatically resize uploaded files. Could you confirm this, please? @Matchdev120 @WorldImpex

**Comment by WorldImpex** [comment]
yes @natalia-muzyka we will not show image requirements here. @Matchdev120 has confirmed that the size of the image does not matter

**Comment by natalia-muzyka** [comment]
Verified and closed.

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 96.0.4664.110
macOS 10.15 // Chrome 96.0.4664.110
