### ISSUE TITLE
The mobile app crashes after an attempt to open a newly created activity

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-backend#1105]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/
geria.test@gmail.com // 123456

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Create a new applet with at least one activity (e.g. with radio, checkbox, and slider items)
3. Log in to the mobile app
4. Tap on the newly created activity
5. Pay attention to the screen

**Actual result**
The mobile app crashes after an attempt to open a newly created activity.

**Expected result**
The activity is opened after tapping the newly created activity.

**Video**: https://www.screencast.com/t/Dtl9kKx23k5

**Notes**
Not reproducible with existing activities/applets

**Environment**
https://admin-staging.mindlogger.org/

geria.test@gmail.com // 123456
applet: test applet

geria2.test@gmail.com	McgzF127
applet: cumulative scores

ML v0.16.37 (staging)
iPhone 6 Plus  // iOS 12.3.1
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
Samsung Galaxy S9 // Android 9.0

crash log(android): 
[https://app.zenhub.com/files/103405378/0bee49f5-1aec-4f17-b1bd-8723cdb0aeae/download](https://app.zenhub.com/files/103405378/0bee49f5-1aec-4f17-b1bd-8723cdb0aeae/download)

**Comment by WorldImpex** [comment]
@natalia-muzyka Are you still experiencing activities crashing at the end on existing applets?

**Comment by natalia-muzyka** [comment]
@WorldImpex yes, but this was caused by a separate issue, I created a [new ticket](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1860) for it.
Nino knows about this.

**Comment by natalia-muzyka** [comment]
Verified as fixed

Environment
https://admin-staging.mindlogger.org/

geria.test@gmail.com // 123456
geria2.test@gmail.com McgzF127
ML v0.16.38 (staging)
iPhone 6 Plus // iOS 12.3.1
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
