### ISSUE TITLE
Infinity loader on admin panel after an attempt to export data (media included)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-backend#1178]
Video: https://www.screencast.com/t/SAjfJ3btEqp5

Environment:
https://admin-staging.mindlogger.org/
account:
josephine_ml@protonmail.com // qwertyui
applet: All items (mobile app only) josephine
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Video: https://www.screencast.com/t/xPE8AKO5OPza

Environment:
https://admin-staging.mindlogger.org/
account:
josephine_ml@protonmail.com // qwertyui
applet: All items (mobile app only) josephine
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
The issue is reproducible: https://www.screencast.com/t/0KG2zQLq3Es

Environment:
https://admin-staging.mindlogger.org/
anita_ml@protonmail.com qwe123!!!
applet: applet name (anita)
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@mtg137 
Still reproducible on the same account and applet.
Video: https://www.screencast.com/t/i3R5lbX6

**Comment by WorldImpex** [comment]
For the short term, lets update the message on the loader to "Please wait for the download to complete. It could take up to 5 minutes depending how much data has been collected. Do not navigate away from this page." 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/3b8ad6a1-5ecd-4e15-b141-facc302d88e5)

**Comment by natalia-muzyka** [comment]
@WorldImpex I was waiting 10 minutes and got a Timeout Errorbut media responses weren't downloaded anyway. 
Probably we need media to be automatically compressed to some acceptable quality (as a future feature)

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/14788be6-dd43-4641-a9cc-aa1a5b79eac3)

**Comment by natalia-muzyka** [comment]
@WorldImpex @mtg137 
[PROD] Infinity loader even if collected data are small.
Activity contains only ~6 Mb video.

https://admin.mindlogger.org/
anita_ml@protonmail.com	qwe123!!!
applet: media items 3
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
it was a connection issue on my side, sorry
