### ISSUE TITLE
Updates to Trails Export/ Drawing

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-backend#1185]
The Y axis is flipped on trails and drawing. Or, I guess maybe transposed (0,<-->100, 90<-->10, etc). After further review it turns out that this is an issue with all drawing canvas tasks. This can be corrected relatively easily post-hoc, but it might be worth figuring out why the axis is flipped and fixing it while chasing down the scaling issue.

**Comment by natalia-muzyka** [comment]
@WorldImpex @mtg137  If I understood the issue correctly, then it is still reproducible, The "y" axis is flipped.
When user draws top-down then the "y" coordinate value should decrease, right?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/bd55c0d2-264e-4172-ab53-2ab6f263d066)

video: https://www.screencast.com/t/MI1tEMWy
export files: https://drive.google.com/drive/folders/194QBWR2EsoGPxbFGak8_kRcPVmANR4ho?usp=sharing

Environment:
https://admin-staging.mindlogger.org/
ML v0.18.31 staging
Samsung Galaxy S9 // Android 10
iPhone 6S // iOS 14.4.2
bernard_ml@protonmail.com	qwe123!!!
applet: A/B trails

**Comment by WorldImpex** [comment]
@natalia-muzyka yes If you draw a line from the top of the page straight down then the Y axis should decrease

**Comment by natalia-muzyka** [comment]
fixed for A/B trails activity:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3b552cb4-b397-47f1-977e-28e5d68548ef)

ML v0.18.37 staging
iPad Pro (10,5-inch) MQDX2 // iOS 15

**Comment by natalia-muzyka** [comment]
Coordinates are fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/81153b04-ac1f-4b82-bd22-0cf00e4e0cc7)

Environment:
ML v0.18.37 staging
iPad Pro (10,5-inch) MQDX2 // iOS 15
https://admin-staging.mindlogger.org/
