### ISSUE TITLE
[PROD] [STAGING] Until user relogin there is only the edited/added activity on the applet screen after saving changes on admin panel and refreshing the app

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-backend#1214]
**Preconditions**
User is logged in on the admin panel
https://admin-staging.mindlogger.org/
The mobile is installed launched
User is logged in

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Edit any activity (e.g. add something in description)
3. Save changes
4. Refresh the mobile app (Home screen)
5. Open the edited applet
6. Pay attention to the screen
7. Sign out/sign in 
8. Open the edited applet
9. Observe the result

**Actual result**
Only the edited activity is displayed on the applet screen after saving changes on the admin panel and refreshing the app Home screen. After log out/log in the issue is not reproducible.

**Expected result**
All the available activities are displayed on the applet screen after saving changes on the admin panel and refreshing the app Home screen

**Video:** https://www.screencast.com/t/kKXRWRmXuehe

**Notes: 
Reproducible on item level as well (Only the edited/added items are displayed on the activity screen after saving changes on admin panel and refreshing the app).
NOT reproducible after log out/log in.**

**Environment:**
https://admin-staging.mindlogger.org/
Applet builder v0.14.0
ML v0.18.49 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 8 Plus // iOS 13.3
anita_ml@protonmail.com	qwe123!!!
applet name (anita)
Applet password:	Qwe123!!!

**Comment by WorldImpex** [comment]
Reproducible in staging 
wavanauken+5@gmail.com/ abcd123
applet: 1214 test 

Comments: The applet does not show up even after logging out and logging back in

**Comment by WorldImpex** [comment]
Works as expected on iPhone 13 Pro

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/ZnjAb2vwc
@WorldImpex should this go as a hotfix or in normal order within the plain milestone release?

Environment:
https://admin-staging.mindlogger.org/
ML v0.18.53 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone Xs Max// iOS 15.3
