### ISSUE TITLE
Arbitrary Server to GCP bucket Investigation 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-backend#1225]

**Comment by devbtech** [comment]
@natalia-muzyka  Arbitrary server is setup with the testing account ( johnadmin@moodle.com / 123123 ) in Dev Environment. Please test/confirm data exports and other relevant stuff is working as expected in general.

**Comment by natalia-muzyka** [comment]
Issues:
The deleted activity remains on the app after refreshing the Home screen#1250

**Comment by natalia-muzyka** [comment]
Works as expected.
Checked manually created and uploaded with github url applets(nimh, dbt, ab trails, cst touch, cst gyro, flanker, subscales, media items, tokenlogger, threshold activities) on:
- creating, updating, deleting applets, activities, items; 
- dataviz and data export;
- refresh response.

Environment:
Win 10 / Chrome 101
macOS Catalina / Chrome 101
ML Pilot v0.19.26 dev
ML v0.20.8 dev
iPhone XR // iOS 14.3
Apple iPad 9th gen (2021) / iOS 15.5
Samsung Galaxy S7 // Android 8
Google Pixel 5a // Android 11
johnadmin@moodle.com / 123123
llinda_ml@protonmail.com / 123456
