### ISSUE TITLE
PROD HotFix - Update all time related export to Epoch Time

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-backend#1231]
In all exports, we should show epoch time in an additional column next to UTC time. 
* Ensure the trails export is updated to absolute epoch time

**Comment by WorldImpex** [comment]
@jj105 This is now changing 

1. Epoch time is shown for regular data export 
2. Epoch time is shown initially and elapsed time in epoch is shown after that for user journey, draw, CST and trails

**Comment by WorldImpex** [comment]
1. Update column names per the below 
2. Add a "UTC_Timestamp" column with the time in UTC 
3. Update epoch column to "epoch_timestamp_seconds" or "epoch_timestamp_seconds_start" 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/a9cf8322-9b78-40cb-8ab4-05f430f003d6)

**Comment by natalia-muzyka** [comment]
@jj105 @devbtech 
I don't see the latest changes on dev or production.
I tried the existing(after refre and newly created CST touch applet, but nothing.
Wasn't there any deployment issue?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8485b097-c829-4239-a020-2b5920f41a0a)

Environment:
https://admin.mindlogger.org/
bernard_ml@protonmail.com	qwe123!!!
https://admin-dev.mindlogger.org/
cst_test@ml.com	123456
stability_task_touch, stability_task_touch(1)
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
@WorldImpex @jj105 
1. lambda is not renamed to lambda_value
2. stim_position is not renamed to stimulus_position
3. use_position column is moved to the end instead of being right next to target_position

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/6457c51f-0519-40b8-bc64-42a0e2c39208)
