### ISSUE TITLE
CST: Decrement Slope 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-backend#1235]
1. Slope should be decremented in the formula and it looks to be incremented. Please update 
2. Update the decrement from 10% to 5%

**Comment by natalia-muzyka** [comment]
@mtg137 @WorldImpex
1 - is this update for both versions (touch and tilt)?
2 - could anyone clarify, please, how should the puck behave after an update? should it move faster or slower after crash?

**Comment by WorldImpex** [comment]
1. Both 
2. It should move faster after the update I believe

**Comment by natalia-muzyka** [comment]
The lambda_slope value is decreased by 5% after every next crash in the calibration phase.
The continuous phase lambda_slope value is always 20 as it was in the previous version.
Checked on iOS:
ML v0.20.1 staging
iPhone XR // iOS 14.3
iPad Pro (10,5-inch) MQDX2 // iOS 15

Waiting on Android build.
