### ISSUE TITLE
Update Epoch time in ms to Epoch time in seconds 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-backend#1240]
Update the epoch time to seconds with ms precision for cognitive and draw items 

The time should have a decimal between seconds and milliseconds 

Epoch time in ms: 1649250456999
Epoch time in seconds with millisecond precision: 1649250456.999

**Comment by natalia-muzyka** [comment]
Actual: Time is updated only in the "epoch_time_in_seconds_start" column. 
Expected: All the columns in the cognitive and draw items are updated to display seconds with ms precision
@WorldImpex please, confirm the expected result

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3bde76ca-907d-45a9-a5aa-6395e243c0bf)

**Comment by WorldImpex** [comment]
@natalia-muzyka Yes that is correct

**Comment by WorldImpex** [comment]
@mtg137 Please also update all nanosecond accuracies to millisecond

**Comment by WorldImpex** [comment]
@natalia-muzyka yes - we should just have it consistent so we need to remove nanosecond and replace it with second with millisecond precision

**Comment by natalia-muzyka** [comment]
Verified as fixed.

Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.75 
macOS BigSur // Chrome 100

**Comment by natalia-muzyka** [comment]
@mtg137 @WorldImpex 
I missed the "milliseconds" and "total time" in A/B Trails, CST and drawing,
they should be updated, and "milliseconds" should be renamed to "seconds" then

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c6827010-fe41-41a6-ac84-7bc2bc726d65)

**Comment by natalia-muzyka** [comment]
@mtg137  the issue is not fixed for drawing item only:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/167cca6d-df5e-421f-a9f4-1bf407c66437)

**Comment by natalia-muzyka** [comment]
Verified as fixed.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7819ccb1-2dc1-496a-b3e8-e2c364151088)

Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.127
