### ISSUE TITLE
Email: There is the unexpected word " by" in the email subject when no user ID is selected

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-backend#1284]
**Preconditions**
The mobile app is installed and launched
The user is logged in:
user-stg@ml.com / 123456

**Steps to reproduce**

1. Complete the activity with configure report and not configured secret ID (config reports v11 / test A)
2. Check the recipient's email (geria.test@gmail.com / 3FuuFz60)
3. Pay attention to the email subject

**Actual result**
There is the unexpected word " by" in the email subject when no user ID is selected

Expected result
There is the "REPORT:" displayed in the email subject 

**Requirements:**
https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=393%3A5938

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/de76119a-cf1a-4e92-9c25-44b70666c1d2)

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com 123456
config reports v11 / test A
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshot: 
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/f7d5f4ec-aa82-4ef8-b587-c84aff800981)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
Re-testing 2 // activity1763
applet password - Qqww!123
