### ISSUE TITLE
Alerts are missing in the admin/email report after selecting the alert option on the mobile app/website

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-backend#1288]
**Preconditions**
Mobile app is installed and launched
User is logged in on mobile app and admin panel
There is the activity with the configured report (summary and export is allowed)
Activity 1. There are no Score IDs in the report
Activity 2. There are Score IDs in the report

**Steps to reproduce**

1. Take an assessment with NO Score IDs on mobile app
2. Select the alert option
3. Pay attention to the mobile Report summary
4. Complete activity
5. Check the recipient's email
6. Pay attention to the first report page
7. Repeat steps 1-6 with the second assessment
8. Check the admin report on user's DataViz
9. Observe the result

**Actual result**
1. Alert box with messages is missing in the admin/email report if there are no Score IDs
2. Alert box contains `${alertsHTML}` after completing the activity with Score IDs

**Expected result:**
Alert messages in the admin and email report match the mobile Report summary

**NOTES: Reproducible after completing the activity on website as well**

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
usr2-stg@ml.com / 123456
applet: Config reports and flows
activity "1" - no Score IDs
activity "3" - with ScoreIDs
Applet password: Qwe123!!!

**Comment by karser** [comment]
@natalia-muzyka I have fixed alerts but am not sure how to reproduce them. Please test.
I deployed the fix to staging and ped(pmhsa) reporting servers.

**Comment by natalia-muzyka** [comment]
@karser I'm sorry for the missing attachments on the ticket. The issue is fixed if there are alerts and Score IDs.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/aef6c997-4dd9-474a-abc1-63ccbc66a005)

But if there are **just alerts with no ScoreIDs** then the issue is reproducible (The report page with the alerts box is missing)

**Expected result:**
If the editor turns on the summary screen without scoreIDs but with alerts:
with alert state (at least one alert option was selected by user) then the alert section should be shown on summary screen and in the report without scoreIDs below.

**Actual result:** 
The Alerts section is not shown in the report after selecting alert options if there are no configured Score IDs on the "Reports" tab. 
Video: https://www.screencast.com/t/ft6xLUY3xlL

**Requirements:**
https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/878
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/aa42a08a-25cc-45d5-8732-7ff9205b05fc)

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
usr2-stg@ml.com / 123456
Config reports and flows
1 - no Score IDs
3 - with ScoreIDs
Applet password: Qwe123!!!

**Comment by DeepDeveloper1996** [comment]
I find out that, issue is from frontend side, for the same applet it is sending different results
![image.png](https://images.zenhubusercontent.com/6315e901f2dc4e6f86d09215/f863c062-ea08-4cfc-a35e-2b913ae4cd73)
![image.png](https://images.zenhubusercontent.com/6315e901f2dc4e6f86d09215/1e6c527c-ab0c-4088-8b10-59828b9a526f)

**Comment by DeepDeveloper1996** [comment]
moreover when I select 2nd option it is sending value=1, and when selected 1st option, it is sending value=null

**Comment by DeepDeveloper1996** [comment]
Through debugging when I have selected 1st option, and replace value=null by value=0, it worked

**Comment by anq83** [comment]
Added fix on web client:
https://github.com/ChildMindInstitute/mindlogger-web/pull/544

**Comment by anq83** [comment]
Asked @karser 
to deploy it on stage

**Comment by anq83** [comment]
deployed on Stage

**Comment by natalia-muzyka** [comment]
@anq83 
Works as expected if the item with the alert option has the option score allowed. 
If the option score is disallowed then the Summary (1st page) is still missing in the report.
Please, check my video: https://www.screencast.com/t/VEgM2dthrC

Environment:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
ML v0.21.54 staging
ML v0.21.57 staging
ML Pilot v0.21.57 prod
Win 10 / Chrome 106
staging account:
usr2-stg@ml.com / 123456
applet: Config reports and flows
activity "1" - no Score IDs, but with scores
activity "1 (1)" - no Score IDs and NO scores
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed.

Environment:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
ML v0.21.59 staging
Win 10 / Chrome 107
staging account:
usr2-stg@ml.com / 123456
applet: Config reports and flows
activity "1" - no Score IDs and NO scores
activity "1 (1)" - no Score IDs, but with scores
applet:  Config reports and flows (Alerts retest)
Applet password: Qwe123!!!

**Comment by yzenchanka** [comment]
Verified as fixed.
Environment:
https://admin-staging.mindlogger.org
https://web-staging.mindlogger.org/
MacOS Monterey 12.0.1 / Safari 15.1
MacOS Monterey 12.0.1 / Chrome 107
Staging account:
userone@ml.com / QAtest123
Test Reports (1)
Applet password: Asd123!!!
