### ISSUE TITLE
[STAGING] User is not able to upload valid images and audio

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-backend#1289]
**Steps to reproduce**

1. Open a site and log in: https://admin-staging.mindlogger.org/
2. Create a new activity or edit existing
3. Add radio item -> Upload header image to the item
4. Add studio stimulus item -> Upload audio to the item
5. Observe the result

**Actual result**
User is not able to upload valid images and audio. Reproduces for all items, splash screen, applet image, activity image, flanker activity(staging only: stimulus, fixation, button image).

**Expected result**
User is able to upload valid images and audio. 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/919110d8-f1e6-4cb8-b0ed-401695b3b33e)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/cf68b57e-bacf-4346-8455-227e21edfaf2)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b72def2e-d0aa-47d1-92ca-fabdf82ef963)

**Files:**
https://drive.google.com/drive/folders/1yFp2CqW3KocgrN-lamdnFc_NW6fwlEPa?usp=sharing

**Environment:**
https://admin-staging.mindlogger.org/
v0.17.18
Win 10 / Chrome 103
ml_general_acc@protonmail.com	/ 12345678

**Comment by MaksimYurys** [comment]
Verified as fixed.

Video:
https://images.zenhubusercontent.com/103405378/385527a2-3f32-4ca0-8d75-b94c85b6e1f1/c969b7a6_4b42_455b_92d4_42eceb95fb36.mp4

Environment:
https://admin.mindlogger.org/ and https://admin-staging.mindlogger.org/
v0.18.0
Win 10 / Chrome 103
JhoneeMind@gmail.com // Qqww!123

**Comment by natalia-muzyka** [comment]
The issue is reproducible on staging again. Admin can't upload images and audio.
Video: https://www.screencast.com/t/7jsAh8rgkin

Win 10 / Chrome 105.0.5195.127

**Comment by natalia-muzyka** [comment]
The issue is not reproducible anymore: 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8de9bc60-97d1-4fa7-b6d0-c1a520e06d9f)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 105
