### ISSUE TITLE
The activity with conditional logic can't be saved

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-backend#1290]
**Steps to reproduce**
1. Open a site and log in: https://admin-staging.mindlogger.org/
2. Create a new activity
3. Add at least two items (e.g. radio and checkbox)
4. Open the Condition logic tab
5. Add the conditional logic(e.g. Screen1 includes Option 1 - IF ALL - Show Screen2)
6. Click "Save"
7. Remove conditional logic
8. Click "Save"
9. Observe the result

**Actual result**
The activity with conditional logic can't be saved

**Expected result**
User can set up and save the activity with the conditional logic

**Video**: https://www.screencast.com/t/M474Ne9Rg8P8

**Environment:**
https://admin-staging.mindlogger.org/
v0.17.18
Win 10 / Chrome 103

**Comment by natalia-muzyka** [comment]
Reproduces after copying activity with conditional logic from the library as well.
Video: https://www.screencast.com/t/BRVM1gTEB

**Comment by MaksimYurys** [comment]
The conditional logic "If (activity) have any state(is shown for the first time/is not shown for the first time)" can't be saved for "Sections".

**Comment by binarybottle** [comment]
Elle: Any conditional logic made prior to the deployment pre-SRC works; however, any edits or new conditional logic does not work. Additionally, some previous conditional logic incorrectly was deleted/cleared, and there is no way to fix it now.

**Comment by yzenchanka** [comment]
Verified as fixed:
Video: https://screencast-o-matic.com/watch/c3QrXDVOkJu
Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 105.0.5195.127
