### ISSUE TITLE
Review AWS and GCP Arbitrary Server Documentation 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-backend#1296]
https://mindlogger.org/guides/aws-server-guide.html

https://mindlogger.org/guides/gcp-server-guide.html

**Comment by karser** [comment]
@binarybottle Here are my notes. I can apply them as a PR to mindlogger-website if you agree or please add your thoughts.

#### 1. I see the confusion here:
1st step: create mindlogger-user
2nd step: create policy for my-mindlogger-bucket
3rd step: create my-mindlogger-bucket bucket

So the user will encounter an error that the my-mindlogger-bucket bucket name is already taken. The bucket name must be unique.
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/ff69a7ab-2aba-41bf-bc51-50f1d4418488)
Then he will pick a name that is available but the policy was already created. If the user forgets to change the bucket name in the policy, AWS credentials will have no access to this bucket and it's a potential source of issues.

I propose we will move the 3rd step before creating the policy of even before creating the user.

#### 1.1 When creating policy there needs to be a note like:

"Please change `my-mindlogger-bucket` according to your bucket name"

#### 2. "Select both credential types (Access key and Password)"
Mindlogger-backend doesn't need password access. Is there another reason to have the password access to AWS console? If not, I suggest we change it to "Select Access key credential type". 

![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/132f52e9-b20c-4870-bc9a-b910ec6cb2e7)

**Comment by binarybottle** [comment]
Sounds great!

**Comment by karser** [comment]
@binarybottle please review my [pull request](https://github.com/ChildMindInstitute/mindlogger-website/pull/91) and tell if we are going in the right direction:

Current version:
https://mindlogger.org/guides/aws-server-guide.html

New version:
https://github.com/ChildMindInstitute/mindlogger-website/blob/a8b1d44f2caac7dbf0a8449948fdaf5fc8c351c7/_posts/2016-09-01-guide-20-aws-server.markdown

- implemented the changes I proposed in my previous comment
- added Set up MongoDB with the YUM package manager
- the docker way is not recommended

How to deal with these links that refer to steps in the **docker** instruction?
I guess I will change them to point to **yum** instead.
![image](https://user-images.githubusercontent.com/1675033/195600790-7a4709e0-2cdc-4f25-96ba-7cfb22face5f.png)

**Comment by karser** [comment]
@binarybottle I completed the GCP tutorial, please merge https://github.com/ChildMindInstitute/mindlogger-website/pull/92
