### ISSUE TITLE
Report file has no extension if "User ID" is turned on in the Email configuration and activity is completed by admin

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-backend#1302]
**Preconditions**
Mobile app is installed and launched
User is logged in on mobile app and admin panel in admin account
There is the activity with the configured report (export is allowed)

**Steps to reproduce**

1. Set up a server, a public key, and a recipient email by clicking the "Configure email" button on the applet level
2. Select the "User ID" checkbox
3. Save configurations and save the applet
4. Refresh the mobile app
5. Take an assessment on the mobile app
6. Proceed to admin panel -> "View users" tab
7. Open the user's Data Viz
8. Click the "Download report" button
9. Pay attention to the report file

**Actual result:**
Report file has no extension if "User ID" is turned on in the Email configuration, but contains appropriate data after opening it.

**Expected result**
Report file has a PDF extension.

**Notes: Not reproducible if activity is completed by user**

**Video:** https://www.screencast.com/t/gJybtbfAdixL

**Environment:**
https://admin-staging.mindlogger.org/
https://admin.mindlogger.org/
Win 10 / Chrome 104
prod: test-user1@com.us / qwerty ; My applet 6 
staging: usr2-stg@ml.com / 123456 ; Config reports and flows 
Applet password: Qwe123!!!

**Comment by TatianaBessonova** [comment]
Verified as fixed.
Environment:
https://admin-staging.mindlogger.org/
Applet builder v0.18.10-alfa
Win 10, Chrome 106
App version 0.21.57
Google Pixel 3 XL, Android 10

**Comment by TatianaBessonova** [comment]
Verified as fixed.
Environment:
https://admin-staging.mindlogger.org/
Applet builder v0.18.10-alfa
Win 10, Chrome 106
App version 0.21.57
Google Pixel 3 XL, Android 10

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Environment:
https://admin-staging.mindlogger.org/
Applet builder v0.18.10-alfa
Win 10 / Chrome 106
macOS 10 / Chrome 106 / Safari 13.1.2
ML v0.21.57 staging
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
